# **pd.melt():**

`pandas.melt()` is used to **transform a wide-format DataFrame into a long-format DataFrame**. This means it takes columns and **turns them into rows**, making our data *tidy* for analysis or plotting.

**`pd.melt()` is Useful when:**

* we have **one or more identifier columns** and the rest are **measured variables**.

* we want to reshape our DataFrame for:
  * Easier `plotting` (e.g., with seaborn or matplotlib).
  * `GroupBy` operations.
  * Exporting tidy data.
  * Feeding into ML models or APIs expecting long-form data.

```python
pd.melt(
    frame= data,         # data is our dataframe
    id_vars=None,        # columns to keep fixed (identifiers)
    value_vars=None,     # columns to unpivot (default: all columns not in id_vars)
    var_name=None,       # name for new 'variable' column
    value_name='value'   # name for new 'value' column
)
```

**Example 1: Basic usage:**

In [12]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Math': [90, 80],
    'Science': [85, 75]
})
df

    Name  Math  Science
0  Alice    90       85
1    Bob    80       75

In [13]:
melted = pd.melt(frame= df,  # our dataframe
                 id_vars='Name',  # Column to keep fixed
                 var_name='Subject', # name for new variable column
                 value_name='Score') # name for new value colmn
melted

    Name  Subject  Score
0  Alice     Math     90
1    Bob     Math     80
2  Alice  Science     85
3    Bob  Science     75

Now it's ready for `groupby`, `aggregation`, or `plotting`.

**Example 2: Melting with multiple `id\_vars`:**

In [17]:
df = pd.DataFrame({
    'Student': ['A', 'B'],
    'Year': [2023, 2023],
    'Math': [90, 80],
    'Science': [88, 78]
})
df

  Student  Year  Math  Science
0       A  2023    90       88
1       B  2023    80       78

In [ ]:
melted = pd.melt(df, # dataframe 
    id_vars=['Student', 'Year'],  # columns to keep fixed 
    var_name='Subject', # name for new variable column
    value_name='Marks')  # name for new value column

melted

  Student  Year  Subject  Marks
0       A  2023     Math     90
1       B  2023     Math     80
2       A  2023  Science     88
3       B  2023  Science     78

**Example 3: When all columns are melted (no id\_vars):**

In [19]:
df = pd.DataFrame({
    'Jan': [100, 200],
    'Feb': [150, 250]
})
df

   Jan  Feb
0  100  150
1  200  250

In [21]:
melted = pd.melt(df, # dataframe 
    var_name='Month', # name for new variable column
    value_name='Sales') # name for new value colmn
melted

  Month  Sales
0   Jan    100
1   Jan    200
2   Feb    150
3   Feb    250

### **opposite** of `pd.melt()`?

The opposite operation is **`pd.pivot()`** or **`pd.pivot_table()`** (if we need aggregation).

In [23]:
# Original wide-format DataFrame
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 87],
    'English': [88, 76, 85]
})

print("Original wide-format DataFrame:")
print(df)
print("="*50)
# Melt the DataFrame (long format)
melted = pd.melt(df, id_vars='Name', var_name='Subject', value_name='Score')

print("\nMelted (long) DataFrame:")
print(melted)
print("="*50)
# Reverse the melt operation using pivot
wide = melted.pivot(index='Name', columns='Subject', values='Score').reset_index()

print("\nReversed (wide) DataFrame:")
print(wide)

Original wide-format DataFrame:
      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       76
2  Charlie    92       87       85
==================================================

Melted (long) DataFrame:
      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     87
6    Alice  English     88
7      Bob  English     76
8  Charlie  English     85
==================================================

Reversed (wide) DataFrame:
Subject     Name  English  Math  Science
0          Alice       88    85       90
1            Bob       76    78       82
2        Charlie       85    92       87

> 🔁 `pd.melt()` → "long format"  
> 
> 🔁 `pd.pivot()` → "wide format"

**Example 4: Full melt-pivot round trip:**

In [24]:
original = pd.DataFrame({
    'Person': ['Tom', 'Jerry'],
    'Jan': [20, 25],
    'Feb': [21, 23]
})
original

  Person  Jan  Feb
0    Tom   20   21
1  Jerry   25   23

In [25]:
#Melt
long_df = pd.melt(original, id_vars='Person', var_name='Month', value_name='Temp')
long_df

  Person Month  Temp
0    Tom   Jan    20
1  Jerry   Jan    25
2    Tom   Feb    21
3  Jerry   Feb    23

In [26]:
# Pivot (to recover original)
wide_df = long_df.pivot(index='Person', columns='Month', values='Temp').reset_index()
wide_df

Month Person  Feb  Jan
0      Jerry   23   25
1        Tom   21   20

**When Not to Use `melt()`:**

* When our data is already in long form.
* If our plan is to do wide-format matrix operations (e.g., correlation matrices, pivot heatmaps).