# **groupby():**

The `pandas.DataFrame.groupby()` method is used to **split** data into groups based on some criteria, **`apply`** a function to each group independently, and then **`combine`** the results back into a DataFrame or Series.

1. **`Split`** the data into groups.
2. **`Apply`** a function to each group (e.g., `sum`, `mean`).
3. **`Combine`** the results into a new DataFrame or Series.

When we call `df.groupby(...)`, it returns a **GroupBy object**.
This object is essentially a **view of the original DataFrame grouped by some key(s)** (like column values).

No computation happens until we call an aggregation or transformation method (e.g., `.sum()`, `.mean()`, etc.).

In [1]:
import pandas as pd

data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Salary': [50000, 52000, 60000, 62000, 58000]
}
df = pd.DataFrame(data)
df

  Department Employee  Salary
0         HR    Alice   50000
1         HR      Bob   52000
2         IT  Charlie   60000
3         IT    David   62000
4    Finance      Eve   58000

In [3]:
grouped = df.groupby('Department')
grouped

> `groupby()` returns a **lazy GroupBy object**.

Now `grouped` is a **GroupBy object**. Nothing has been computed yet.

### **Aggregation Methods (trigger computation):**  

We **trigger computation** using methods like `.sum()`, `.mean()`, `.agg()`, `.transform()`:

| Method              | Description                       |
| ------------------- | --------------------------------- |
| `.sum()`            | Sum of each group                 |
| `.mean()`           | Mean of each group                |
| `.median()`         | Median                            |
| `.count()`          | Count of non-NA entries per group |
| `.size()`           | Number of rows per group          |
| `.min()` / `.max()` | Min / Max of each group           |
| `.std()` / `.var()` | Standard deviation / Variance     |

> `sum()`, `mean()`, `min()`, `max()`, `count()`, `size()`, `first()`, `last()`, `median()`, `std()`, `var()`, `sem()`

In [ ]:
grouped['Salary'].sum()  # total salary per department

Department
Finance     58000
HR         102000
IT         122000
Name: Salary, dtype: int64

### **Transformation / Filtering:**

| Method         | Description                                                  |
| -------------- | ------------------------------------------------------------ |
| `.transform()` | Returns object of same shape; useful for feature engineering |
| `.filter()`    | Filters groups based on a condition                          |
| `.apply()`     | Apply a custom function to each group                        |
| `.agg()`       | Apply multiple aggregation functions                         |

In [8]:
# Add a column showing salary mean of each department
df['Dept_Avg_Salary'] = grouped['Salary'].transform('mean')
df

  Department Employee  Salary  Dept_Avg_Salary
0         HR    Alice   50000          51000.0
1         HR      Bob   52000          51000.0
2         IT  Charlie   60000          61000.0
3         IT    David   62000          61000.0
4    Finance      Eve   58000          58000.0

### **Iterating over groups:**

In [25]:
grouped

In [9]:
for name, group in grouped:
    print(f"Group: {name}")
    print(group)

Group: Finance
  Department Employee  Salary  Dept_Avg_Salary
4    Finance      Eve   58000          58000.0
Group: HR
  Department Employee  Salary  Dept_Avg_Salary
0         HR    Alice   50000          51000.0
1         HR      Bob   52000          51000.0
Group: IT
  Department Employee  Salary  Dept_Avg_Salary
2         IT  Charlie   60000          61000.0
3         IT    David   62000          61000.0

## **GroupBy Object Attributes:**

- `.groups`: dict of group name → row indices

- `.ngroups`: number of groups

- `.keys`: Keys used for grouping 

- `.size`: group sizes

- `.dtypes`: data types of grouped columns

- `.axes`: index/columns of the groups

- `.grouper`: internal Grouper object

- `.name`: name of the grouping column (if only one)

In [16]:
grouped = df.groupby('Department')
print(dir(grouped))

['Department', 'Dept_Avg_Salary', 'Employee', 'Salary', '_DataFrameGroupBy__examples_dataframe_doc', '__annotations__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_accessors', '_agg_examples_doc', '_agg_general', '_agg_py_fallback', '_aggregate_frame', '_aggregate_with_numba', '_apply_filter', '_apply_to_column_groupbys', '_ascending_count', '_choose_path', '_concat_objects', '_constructor', '_cumcount_array', '_cython_agg_general', '_cython_transform', '_define_paths', '_deprecate_axis', '_descending_count', '_dir_additions', '_dir_deletions', '_fill', '_get_data_to_aggregate', '_get_index', '_get_indices', '_gotitem', '_grouper', '_hidden_attrs', '_idxmax_idxmin', '_infer_selection', '_insert_inaxis_grouper', '_internal_names', '_internal_names_set', '_make_mask_from_int', '_make_mask_from_list', '_make_mask_from_positional_indexer', '_make_mask_from_slice', '_make_mask_from_tuple', '_mask_selected_obj', '_maybe_transpose_result', '_nth', '_numba_agg_general', '_numba_prep', '_obj_1d_constructor', '_obj_with_exclusions', '_op_via_apply', '_positional_selector', '_python_agg_general', '_python_apply_general', '_reindex_output', '_reset_cache', '_selected_obj', '_selection', '_selection_list', '_set_result_index_ordered', '_transform', '_transform_general', '_transform_with_numba', '_value_counts', '_wrap_agged_manager', '_wrap_aggregated_output', '_wrap_applied_output', '_wrap_applied_output_series', '_wrap_idxmax_idxmin', '_wrap_transform_fast_result', 'agg', 'aggregate', 'all', 'any', 'apply', 'bfill', 'boxplot', 'corr', 'corrwith', 'count', 'cov', 'cumcount', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'dtypes', 'ewm', 'expanding', 'ffill', 'fillna', 'filter', 'first', 'get_group', 'groups', 'head', 'hist', 'idxmax', 'idxmin', 'indices', 'last', 'max', 'mean', 'median', 'min', 'ndim', 'ngroup', 'ngroups', 'nth', 'nunique', 'ohlc', 'pct_change', 'pipe', 'plot', 'prod', 'quantile', 'rank', 'resample', 'rolling', 'sample', 'sem', 'shift', 'size', 'skew', 'std', 'sum', 'tail', 'take', 'transform', 'value_counts', 'var']

In [11]:
grouped.groups    # {'Finance': [4], 'HR': [0, 1], 'IT': [2, 3]}

{'Finance': [4], 'HR': [0, 1], 'IT': [2, 3]}

In [12]:
grouped.ngroups   # 3

3

In [14]:
grouped.keys

'Department'

In [15]:
grouped.dtypes

C:\Users\MyMachine\AppData\Local\Temp\ipykernel_7368\1974849099.py:1: FutureWarning: DataFrameGroupBy.dtypes is deprecated and will be removed in a future version. Check the dtypes on the base object instead
  grouped.dtypes

           Department Employee Salary Dept_Avg_Salary
Department
Finance        object   object  int64         float64
HR             object   object  int64         float64
IT             object   object  int64         float64

## **Grouping by Multiple Columns:**

In [13]:
df.groupby(['Department', 'Employee']).sum()

                     Salary  Dept_Avg_Salary
Department Employee
Finance    Eve        58000          58000.0
HR         Alice      50000          51000.0
           Bob        52000          51000.0
IT         Charlie    60000          61000.0
           David      62000          61000.0

### **Other useful GroupBy methods:**

> `head()`, `tail()`, `nth()`, `describe()`, `fillna()`, `as_index()`, `get_group()`

In [21]:
grouped.nth(n= 1)

  Department Employee  Salary  Dept_Avg_Salary
1         HR      Bob   52000          51000.0
3         IT    David   62000          61000.0

In [17]:
grouped.head()

  Department Employee  Salary  Dept_Avg_Salary
0         HR    Alice   50000          51000.0
1         HR      Bob   52000          51000.0
2         IT  Charlie   60000          61000.0
3         IT    David   62000          61000.0
4    Finance      Eve   58000          58000.0

In [22]:
grouped.describe()

           Salary                                                            \
            count     mean          std      min      25%      50%      75%
Department
Finance       1.0  58000.0          NaN  58000.0  58000.0  58000.0  58000.0
HR            2.0  51000.0  1414.213562  50000.0  50500.0  51000.0  51500.0
IT            2.0  61000.0  1414.213562  60000.0  60500.0  61000.0  61500.0

                    Dept_Avg_Salary                                           \
                max           count     mean  std      min      25%      50%
Department
Finance     58000.0             1.0  58000.0  NaN  58000.0  58000.0  58000.0
HR          52000.0             2.0  51000.0  0.0  51000.0  51000.0  51000.0
IT          62000.0             2.0  61000.0  0.0  61000.0  61000.0  61000.0


                75%      max
Department
Finance     58000.0  58000.0
HR          51000.0  51000.0
IT          61000.0  61000.0

In [24]:
grouped.get_group('IT')

  Department Employee  Salary  Dept_Avg_Salary
2         IT  Charlie   60000          61000.0
3         IT    David   62000          61000.0