# **Aggregation:**

In **pandas**, `.agg()` and `.aggregate()` are **used to apply one or more aggregation functions** (like `sum()`, `mean()`, `min()`, etc.) on a `DataFrame` or `Series`. They are **aliases of each other**, so `.agg()` and `.aggregate()` behave the same.

**They’re commonly used with:**

* `groupby()` for grouped aggregation.
* `DataFrame`/`Series` directly for column-wise or row-wise aggregation.

```python
DataFrame.agg(func, axis=0, *args, **kwargs)
```

* `func`: A single function, list of functions, or a dictionary of column-function mappings.
* `axis=0`: Aggregation is applied column-wise (default).
* `axis=1`: Aggregation is applied row-wise.

### ▶ **1. Aggregating a DataFrame using a single function:**

In [39]:
import pandas as pd

# Sample DataFrame
data = {
    'Math': [90, 80, 70, 60],
    'Science': [88, 76, 95, 89],
    'English': [78, 85, 88, 92]
}

df = pd.DataFrame(data)
print(df)
print("-"*25)

# Apply a single aggregation function: mean
mean_values = df.agg('mean')  # or df.aggregate('mean')
print("Column-wise mean:")
print(mean_values)

   Math  Science  English
0    90       88       78
1    80       76       85
2    70       95       88
3    60       89       92
-------------------------
Column-wise mean:
Math       75.00
Science    87.00
English    85.75
dtype: float64

This calculates the **mean of each column**.

### ▶ **2. Aggregating with multiple functions:**

In [40]:
df

   Math  Science  English
0    90       88       78
1    80       76       85
2    70       95       88
3    60       89       92

In [41]:
# Apply multiple aggregation functions to each column
multi_agg = df.agg(['mean', 'min', 'max'])
print("Multiple aggregations:")
multi_agg

Multiple aggregations:

      Math  Science  English
mean  75.0     87.0    85.75
min   60.0     76.0    78.00
max   90.0     95.0    92.00

This gives `mean`, `min`, and `max` for each column.

In [42]:
df

   Math  Science  English
0    90       88       78
1    80       76       85
2    70       95       88
3    60       89       92

In [43]:
# Apply multiple aggregation functions for  each row for numeric values only:
multi_agg = df[["Math", "Science", "English"]].agg(['mean', 'min', 'max'], axis= 1)
print("Multiple aggregations:")
multi_agg

Multiple aggregations:

        mean   min   max
0  85.333333  78.0  90.0
1  80.333333  76.0  85.0
2  84.333333  70.0  95.0
3  80.333333  60.0  92.0

### ▶ **3. Aggregating different functions per column using a dictionary:**

In [44]:
df

   Math  Science  English
0    90       88       78
1    80       76       85
2    70       95       88
3    60       89       92

In [45]:
# Custom aggregation for each column
custom_agg = df.agg({
    'Math': ['mean', 'std'],
    'Science': ['min', 'max'],
    'English': 'sum'
})
print("Custom aggregation per column:")
print(custom_agg)

Custom aggregation per column:
           Math  Science  English
mean  75.000000      NaN      NaN
std   12.909944      NaN      NaN
min         NaN     76.0      NaN
max         NaN     95.0      NaN
sum         NaN      NaN    343.0

Dictionary syntax lets you **specify different aggregations per column**.

### ▶ **4. Row-wise aggregation (`axis=1`):**

In [46]:
df

   Math  Science  English
0    90       88       78
1    80       76       85
2    70       95       88
3    60       89       92

In [47]:
# Aggregate across rows instead of columns
row_wise_sum = df.agg('sum', axis=1)
print("Row-wise sum:")
row_wise_sum

Row-wise sum:

0    256
1    241
2    253
3    241
dtype: int64

This gives **total marks per student** (row-wise sum).

### ▶ **5. With `groupby()`:**

In [48]:
# Sample DataFrame with groups
data = {
    'Student': ['Alice', 'Bob', 'Alice', 'Bob'],
    'Subject': ['Math', 'Math', 'Science', 'Science'],
    'Score': [90, 80, 85, 75]
}
df2 = pd.DataFrame(data)
df2

  Student  Subject  Score
0   Alice     Math     90
1     Bob     Math     80
2   Alice  Science     85
3     Bob  Science     75

In [49]:
# Group by student and aggregate scores
grouped = df2.groupby('Student')['Score'].agg(['mean', 'max'])
print("\nGroupby aggregation:")
grouped

Groupby aggregation:

         mean  max
Student
Alice    87.5   90
Bob      77.5   80

Useful when you want to **summarize grouped data**.

---
---
---

## **`agg()` with user-defined functions (UDFs):**

In [50]:
import pandas as pd
import numpy as np

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math': [90, 80, 70, 60],
    'Science': [88, 76, 95, 89],
    'English': [78, 85, 88, 92]
}

df = pd.DataFrame(data)
df

      Name  Math  Science  English
0    Alice    90       88       78
1      Bob    80       76       85
2  Charlie    70       95       88
3    David    60       89       92

### **1. Using a custom function defined with `def`:**

In [51]:
# Custom function: range of values
def value_range(series):
    return series.max() - series.min()

# Apply custom function to all columns
result = df[['Math', 'Science', 'English']].agg(value_range)
print("Value range (max - min) for each subject:")
print(result)

Value range (max - min) for each subject:
Math       30
Science    19
English    14
dtype: int64

### **2. Using `lambda` functions:**

In [52]:
# Use a lambda function directly
result = df[['Math', 'Science', 'English']].agg(lambda x: x.mean() + x.std())
print("\nMean + Std Dev for each subject:")
print(result)

Mean + Std Dev for each subject:
Math       87.909944
Science    94.958224
English    91.659033
dtype: float64

### **3. Using multiple custom functions:**

In [53]:
# Define custom functions
def custom_stat1(x):
    return x.mean() * 2

def custom_stat2(x):
    return np.median(x)

# Apply multiple custom functions
result = df[['Math', 'Science']].agg([custom_stat1, custom_stat2])
print("\nMultiple custom functions applied to Math and Science:")
print(result)

ValueError: cannot combine transform and aggregation operations

### **4. Using a dictionary to apply different custom functions to different columns:**

In [ ]:
# Define functions
def range_fn(x):
    return x.max() - x.min()

def mean_plus_std(x):
    return x.mean() + x.std()

# Use dictionary to map columns to custom functions
result = df.agg({
    'Math': range_fn,
    'Science': mean_plus_std,
    'English': lambda x: x.sum() / len(x)  # same as mean
})
print("\nDifferent custom functions per column:")
print(result)

Different custom functions per column:
Math       30.000000
Science    94.958224
English    85.750000
dtype: float64

### **5. Custom aggregation with `groupby()`:**

In [ ]:
import warnings
warnings.filterwarnings("ignore")
# Group by the first letter of name
df['Group'] = df['Name'].str[0]  # A, B, C, D

# Group by 'Group' and aggregate scores
grouped = df.groupby('Group', observed=True)[['Math', 'Science', 'English']].agg({
    'Math': lambda x: x.max() - x.min(),  # range
    'Science': np.mean,                   # mean
    'English': np.std                     # standard deviation
})
print("\nGroupby with custom aggregation functions:")
print(grouped)

Groupby with custom aggregation functions:
       Math  Science  English
Group
A         0     88.0      NaN
B         0     76.0      NaN
C         0     95.0      NaN
D         0     89.0      NaN

### **6. Returning a named custom metric:**

In [ ]:
# Custom function that returns a named value
def score_summary(x):
    return pd.Series({
        'range': x.max() - x.min(),
        'custom_avg': (x.mean() + x.median()) / 2
    })

# Apply to a column
summary = df['Math'].agg(score_summary)
print("\nNamed summary statistics for Math:")
print(summary)

Named summary statistics for Math:
range         30.0
custom_avg    75.0
dtype: float64

| Type             | Example                            |
| ---------------- | ---------------------------------- |
| Single function  | `df.agg(my_func)`                  |
| Lambda function  | `df.agg(lambda x: x.mean())`       |
| Multiple funcs   | `df.agg([func1, func2])`           |
| Dict mapping     | `df.agg({'col1': f1, 'col2': f2})` |
| With `groupby()` | `df.groupby(...).agg(...)`         |

---
------
---

## **Numpy and Pandas Functions for `agg()`:**

**1. Built-in pandas Aggregation Functions:**

* `'sum'`
* `'mean'`
* `'median'`
* `'min'`
* `'max'`
* `'std'`
* `'var'`
* `'count'`
* `'nunique'`
* `'prod'`
* `'size'` (for `groupby` objects)
* `'first'`
* `'last'`
* `'sem'` (Standard error of the mean)
* `'mad'` (Mean absolute deviation)
* `'skew'`
* `'kurt'` (Kurtosis)

**2. NumPy Aggregation Functions:**

* `np.sum`
* `np.mean`
* `np.median`
* `np.min`
* `np.max`
* `np.std`
* `np.var`
* `np.prod`
* `np.ptp` (Peak to peak – range)
* `np.percentile`
* `np.quantile`
* `np.average`

**3. Other Usable Functions:**

**We can also pass:**

1. Custom functions (`def` or `lambda`)
2. Functions from `scipy.stats` (e.g., `mode`, `iqr`, etc.)
3. Any function that takes a 1D array/Series and returns a single scalar