# **`df.select_dtypes()`:**

- `select_dtypes()` is used to **select columns in a DataFrame based on their data types**.

- We use `select_dtypes()` when we want to:

    * **Filter numeric columns only**
    * **Exclude object or categorical columns**
    * **Apply operations to specific data types** (e.g., scale only `float` columns)

```python
df.select_dtypes(include=None, exclude=None)
```

* `include`: List of dtypes to include (e.g., `'number'`, `'object'`, `'category'`, `'datetime'`)

* `exclude`: List of dtypes to exclude

**Common dtype strings:**

| Alias        | Matches                            |
| ------------ | ---------------------------------- |
| `'number'`   | All numeric types (`int`, `float`) |
| `'object'`   | Text/string columns                |
| `'category'` | Categorical columns                |
| `'bool'`     | Boolean columns                    |
| `'datetime'` | `datetime64` columns               |

**Example 1 – Select only numeric columns:**

In [1]:
import pandas as pd

df = pd.DataFrame({
    'age': [25, 30, 45],
    'salary': [50000.0, 60000.0, 80000.0],
    'name': ['Alice', 'Bob', 'Charlie'],
    'joined': pd.to_datetime(['2020-01-01', '2021-03-01', '2022-07-01'])
})
df

   age   salary     name     joined
0   25  50000.0    Alice 2020-01-01
1   30  60000.0      Bob 2021-03-01
2   45  80000.0  Charlie 2022-07-01

In [3]:
numeric_df = df.select_dtypes(include='number')
numeric_df

   age   salary
0   25  50000.0
1   30  60000.0
2   45  80000.0

**Example 2 – Exclude object (string) columns:**

In [4]:
df

   age   salary     name     joined
0   25  50000.0    Alice 2020-01-01
1   30  60000.0      Bob 2021-03-01
2   45  80000.0  Charlie 2022-07-01

In [5]:
non_object_df = df.select_dtypes(exclude='object')
non_object_df

   age   salary     joined
0   25  50000.0 2020-01-01
1   30  60000.0 2021-03-01
2   45  80000.0 2022-07-01

**Example 3 – Select multiple types:**

In [6]:
df

   age   salary     name     joined
0   25  50000.0    Alice 2020-01-01
1   30  60000.0      Bob 2021-03-01
2   45  80000.0  Charlie 2022-07-01

In [7]:
df.select_dtypes(include=['float', 'datetime'])

    salary     joined
0  50000.0 2020-01-01
1  60000.0 2021-03-01
2  80000.0 2022-07-01

This selects all `float` and `datetime` columns.