# **Filtering `Dataframe.query()` Method:**

The `DataFrame.query()` method in pandas allows you to filter DataFrames using a string expression that resembles natural language, making your code more readable and intuitive compared to traditional boolean indexing.

> `DataFrame.query(expr, inplace=False, **kwargs)`

The `expr` parameter is a string containing the query expression that evaluates to a boolean condition.

### **When It's Useful:**

**The `query()` method is particularly valuable when:**

- You have complex filtering conditions that would be verbose with traditional boolean indexing

- Column names contain spaces or special characters

- You want more readable code that resembles SQL-like syntax

- You need to combine multiple conditions with logical operators

- You're working with large datasets where query optimization matters

#### **1. Basic Filtering:**

In [18]:
import pandas as pd 

# Sample data
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'age': [25, 30, 35, 28, 32],
    'salary': [50000, 60000, 70000, 55000, 65000],
    'department': ['HR', 'IT', 'Finance', 'HR', 'IT']
})
df

      name  age  salary department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR
4      Eve   32   65000         IT

In [ ]:
# Traditional way 
result1 = df[df['age'] > 30]

# Using query() - more readable
result2 = df.query('age > 30')

In [2]:
result1

      name  age  salary department
2  Charlie   35   70000    Finance
4      Eve   32   65000         IT

In [3]:
result2

      name  age  salary department
2  Charlie   35   70000    Finance
4      Eve   32   65000         IT

#### **2. Multiple Conditions:**

In [19]:
df

      name  age  salary department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR
4      Eve   32   65000         IT

In [4]:
# Traditional way - can get messy
result1 = df[(df['age'] > 25) & (df['salary'] < 65000)]

# Using query() - cleaner
result2 = df.query('age > 25 and salary < 65000')

In [5]:
result1

    name  age  salary department
1    Bob   30   60000         IT
3  Diana   28   55000         HR

In [6]:
result2

    name  age  salary department
1    Bob   30   60000         IT
3  Diana   28   55000         HR

#### **3. Working with Column Names Containing Spaces:**

In [21]:
# DataFrame with spaces in column names
df_spaces = pd.DataFrame({
    'first name': ['Alice', 'Bob', 'Charlie'],
    'last name': ['Smith', 'Jones', 'Brown'],
    'annual salary': [50000, 60000, 70000]
})
df_spaces

  first name last name  annual salary
0      Alice     Smith          50000
1        Bob     Jones          60000
2    Charlie     Brown          70000

In [ ]:
# Traditional way requires backticks or brackets
result1 = df_spaces[df_spaces['annual salary'] > 55000]

# Using query() with backticks for spaced names
result2 = df_spaces.query('`annual salary` > 55000')

In [8]:
result1

  first name last name  annual salary
1        Bob     Jones          60000
2    Charlie     Brown          70000

In [9]:
result2

  first name last name  annual salary
1        Bob     Jones          60000
2    Charlie     Brown          70000

### **4. String Operations:**

In [22]:
df

      name  age  salary department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR
4      Eve   32   65000         IT

In [23]:
# Filter by string conditions
result_a = df.query('department == "IT"')

# String contains
result = df.query('name.str.contains("a", case=False)')

In [24]:
result_a

  name  age  salary department
1  Bob   30   60000         IT
4  Eve   32   65000         IT

In [11]:
result

      name  age  salary department
0    Alice   25   50000         HR
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR

#### **5. Using Variables in Queries:**

In [25]:
df

      name  age  salary department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR
4      Eve   32   65000         IT

In [13]:
min_age = 28
target_dept = 'HR'

# Use @ to reference external variables
result = df.query('age >= @min_age and department == @target_dept')
result

    name  age  salary department
3  Diana   28   55000         HR

#### **6. Complex Expressions:**

In [26]:
df

      name  age  salary department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR
4      Eve   32   65000         IT

In [30]:
# Multiple conditions with different operators
result_b = df.query('age > 25 and (department == "IT" or salary > 60000)')

# Using isin() equivalent
departments = ['IT', 'Finance']
result_c = df.query('department in @departments')

In [31]:
result_b

      name  age  salary department
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
4      Eve   32   65000         IT

In [32]:
result_c

      name  age  salary department
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
4      Eve   32   65000         IT

#### **7. Index-based Queries:**

In [33]:
df

      name  age  salary department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000    Finance
3    Diana   28   55000         HR
4      Eve   32   65000         IT

In [36]:
# Set age as index
df_indexed = df.set_index('age')

# Query on index
result_z = df_indexed.query('age > 28 and age < 35')

In [35]:
df_indexed

        name  salary department
age
25     Alice   50000         HR
30       Bob   60000         IT
35   Charlie   70000    Finance
28     Diana   55000         HR
32       Eve   65000         IT

In [37]:
result_z

    name  salary department
age
30   Bob   60000         IT
32   Eve   65000         IT

#### **8. Comparison with Traditional Methods:**

In [38]:
# Traditional boolean indexing
mask = (df['age'] > 25) & (df['salary'] < 65000) & (df['department'].isin(['IT', 'HR']))
traditional_result = df[mask]

# Equivalent query() - more readable
query_result = df.query('age > 25 and salary < 65000 and department in ["IT", "HR"]')

In [39]:
traditional_result

    name  age  salary department
1    Bob   30   60000         IT
3  Diana   28   55000         HR

In [40]:
query_result

    name  age  salary department
1    Bob   30   60000         IT
3  Diana   28   55000         HR

The `query()` method can be faster for large DataFrames because it uses numexpr under the hood for optimization when available. However, for small DataFrames, traditional boolean indexing might be slightly faster due to less overhead.

### **Limitations:**

   - String expressions need to be valid Python expressions
   - Some complex operations might still require traditional indexing
   - Column names with special characters need backticks
   - Less IDE support for syntax highlighting and autocomplete compared to regular Python code