# **Lable based Filtering:**

The `.filter()` method is used to **select rows or columns** from a DataFrame based on **labels (names)** — not values. It's a **`label-based`** filter, unlike `.iloc` (which is index-based) or `.loc` (which is label + condition based).

```python
> DataFrame.filter(items=None, like=None, regex=None, axis=None)
```

* **`items`** → List of exact labels (e.g., column or row names).
* **`like`** → Substring to match in labels.
* **`regex`** → Regular expression pattern to match labels.
* **`axis`** → `0` (rows) or `1` (columns); defaults to `0`.

**Example Setup:**

In [2]:
import pandas as pd

data = {
    "Customer_ID": [1, 2, 3],
    "Customer_Name": ["Alice", "Bob", "Charlie"],
    "Customer_Age": [25, 30, 35],
    "Product_Purchased": ["Laptop", "Tablet", "Phone"],
    "Purchase_Amount": [1200, 800, 600]
}

df = pd.DataFrame(data)
df

   Customer_ID Customer_Name  Customer_Age Product_Purchased  Purchase_Amount
0            1         Alice            25            Laptop             1200
1            2           Bob            30            Tablet              800
2            3       Charlie            35             Phone              600

**`Example 1`: Select specific columns using `items`:**

In [3]:
# Select exact columns by name
df.filter(items=["Customer_Name", "Purchase_Amount"], axis=1)

  Customer_Name  Purchase_Amount
0         Alice             1200
1           Bob              800
2       Charlie              600

This returns a new DataFrame with only `Customer_Name` and `Purchase_Amount`.

**`Example 2`: Select columns containing a substring using `like`:**

In [4]:
# Select columns whose names contain "Customer"
df.filter(like="Customer", axis=1)

   Customer_ID Customer_Name  Customer_Age
0            1         Alice            25
1            2           Bob            30
2            3       Charlie            35

**`Example 3`: Select columns using `regex`:**

In [5]:
# Select columns starting with "Product"
df.filter(regex="^Product", axis=1)

  Product_Purchased
0            Laptop
1            Tablet
2             Phone

**`Example 4`: Filter rows by index label (less common, but possible):**

In [7]:
# Set index first
df_with_index = df.set_index("Customer_ID")
df_with_index

            Customer_Name  Customer_Age Product_Purchased  Purchase_Amount
Customer_ID
1                   Alice            25            Laptop             1200
2                     Bob            30            Tablet              800
3                 Charlie            35             Phone              600

In [8]:
# Select specific rows by index label
df_with_index.filter(items=[1, 3], axis=0)

  Customer_Name  Customer_Age Product_Purchased  Purchase_Amount
1         Alice            25            Laptop             1200
3       Charlie            35             Phone              600

#### **When to use `.filter()`?**

* When you want to **match multiple columns based on patterns** (e.g., all columns starting with "Customer").

* When you want a **cleaner alternative to `df.loc[:, ...]` or `df[[...]]`** for label-based filtering.

* When working with **high-dimensional data** (e.g., many columns or hierarchical index).


| Use Case            | Recommended Method               |
| ------------------- | -------------------------------- |
| Exact column names  | `df.filter(items=[...], axis=1)` |
| Substring in names  | `df.filter(like="...", axis=1)`  |
| Regex pattern match | `df.filter(regex="...", axis=1)` |
| Filter by row index | `df.filter(..., axis=0)`                |

---
---
---

## **`DataFrame.set_index()` Method:**

The `dataframe.set_index()` method is used to set one or more columns of a DataFrame as its index. This can enhance the organization of data and improve the efficiency of data retrieval and manipulation.

**`Data Alignment`**:   
When performing operations between DataFrames, aligned indices can help ensure correct alignment of data.

**`Hierarchical Indexing`**:  
You can create a multi-level index (hierarchical index) for more complex data structures.

##### **1. Simple Indexing:**  
Suppose we have a DataFrame with sales data, and we want to set the "Date" column as the index:

In [10]:
import pandas as pd

data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03'],
    'Sales': [200, 250, 300]
}

df = pd.DataFrame(data)
df.set_index('Date', inplace=True)
df

            Sales
Date
2023-01-01    200
2023-01-02    250
2023-01-03    300

##### **2. Multi-level Indexing:**   
We might want to analyze sales data by region and product. 

We can create a hierarchical index:

In [12]:
data = {
    'Region': ['North', 'North', 'South', 'South'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [200, 150, 300, 250]
}

df = pd.DataFrame(data)
df

  Region Product  Sales
0  North       A    200
1  North       B    150
2  South       A    300
3  South       B    250

In [13]:
df.set_index(['Region', 'Product'], inplace=True)
df

                Sales
Region Product
North  A          200
       B          150
South  A          300
       B          250

##### **3. Resetting the Index:**
If we need to revert back to the default integer index, we can use `reset_index()`:

In [14]:
df

                Sales
Region Product
North  A          200
       B          150
South  A          300
       B          250

In [15]:
df.reset_index(inplace=True)
df

  Region Product  Sales
0  North       A    200
1  North       B    150
2  South       A    300
3  South       B    250

##### **4. Data Alignment During Merge:**
If we are merging two DataFrames, having a properly set index can help ensure that the data aligns correctly:

In [19]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value2': [4, 5, 6]})
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [20]:
df2

  Key  Value2
0   A       4
1   B       5
2   C       6

In [22]:
df1.set_index('Key', inplace=True)
df2.set_index('Key', inplace=True)

merged_df = df1.join(df2)
merged_df

     Value1  Value2
Key
A         1       4
B         2       5
C         3       6

The `set_index()` method is a powerful tool in pandas that allows for better organization of data and facilitates complex data operations. By setting meaningful indices, you can improve both the readability and performance of your DataFrame manipulations.