# **Stacking:**

## **NumPy Stacking:**

#### **1. Horizontal Stacking (Side-by-side / column-wise):**

> `np.hstack()`    
> 
> or 
> 
> `np.concatenate(..., axis=1)`
> 

* Joins arrays **`along columns`**.
* Arrays must have the **`same number of rows`** (same shape along `axis=0`).

In [1]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [2]:
a

array([[1, 2],
       [3, 4]])

In [3]:
b

array([[5, 6],
       [7, 8]])

In [4]:
# Horizontal stacking
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### **2. Vertical Stacking (Top-to-bottom / row-wise):**

> `np.vstack()` 
> 
> or 
> 
> `np.concatenate(..., axis=0)`

* Joins arrays **`along rows`**.
* Arrays must have the **`same number of columns`** (same shape along `axis=1`).

In [6]:
# Vertical stacking
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
# or
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## **Pandas Stacking:**

In pandas, we typically work with **`Series`** and **`DataFrames`**.

##### **1. Horizontal Stacking in pandas:**

> `pd.concat([...], axis=1)`

Also: 
> `DataFrame.join()` or 
> 
> `DataFrame.merge()` (for key-based joins)

* Adds **`columns`** side-by-side.
* Useful when combining features or multiple datasets with the same index.

In [8]:
import pandas as pd

s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

In [9]:
s1

0    1
1    2
2    3
dtype: int64

In [10]:
s2

0    4
1    5
2    6
dtype: int64

In [11]:
# Horizontal stacking
pd.concat([s1, s2], axis=1)

   0  1
0  1  4
1  2  5
2  3  6

##### **2. Vertical Stacking in pandas:**

> `pd.concat([...], axis=0)`

* Adds **`rows`** on top of each other.
* Useful when stacking data with the same columns.

In [12]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

In [13]:
df1

   A  B
0  1  3
1  2  4

In [14]:
df2

   A  B
0  5  7
1  6  8

In [15]:
# Vertical stacking
pd.concat([df1, df2], axis=0)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

> Use `ignore_index=True` if you want to reset row numbers.

| Stacking Type  | NumPy Function                             | pandas Equivalent          |
| -------------- | ------------------------------------------ | -------------------------- |
| **Horizontal** | `np.hstack()` / `concatenate(..., axis=1)` | `pd.concat([...], axis=1)` |
| **Vertical**   | `np.vstack()` / `concatenate(..., axis=0)` | `pd.concat([...], axis=0)` |