# **Data Preparation:**

In [1]:
import pandas as pd
import numpy as np
import warnings

In [2]:
data= pd.read_csv("https://raw.githubusercontent.com/rajesh-coventry/Projects/refs/heads/master/00_DataSets/31_uber_dataset.csv")
data.shape

(200000, 9)

In [3]:
warnings.filterwarnings("ignore")

In [4]:
data.columns

Index(['Unnamed: 0', 'key', 'fare_amount', 'pickup_datetime',
       'pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude', 'passenger_count'],
      dtype='object')

In [5]:
data.head(3)

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1

In [ ]:
# Rename columns: Unnamed 0 to id and 
# key to date
data.rename(columns={"Unnamed: 0": "id", "key": "date"}, inplace=True)

In [14]:
data.columns

Index(['id', 'datetime', 'fare_amount', 'pickup_datetime', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object')

| Column Name        | Description                         |
| ------------------ | ----------------------------------- |
| id                 | Unique id   entifier                |
| date= pickup time  | datetime as uniqe identifier        |
| fare\_amount       | Total fare (USD)                    |
| pickup\_datetime   | Timestamp of pickup                 |
| pickup\_longitude  | Pickup location (longitude)         |
| pickup\_latitude   | Pickup location (latitude)          |
| dropoff\_longitude | Dropoff location (longitude)        |
| dropoff\_latitude  | Dropoff location (latitude)         |
| passenger\_count   | Number of passengers                |

In [ ]:
data.head(3)

,id,datetime,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1

In [18]:
data.shape

(200000, 9)

In [17]:
data["id"].nunique()

200000

The `id` coluumn will be used as the unique identifier for this dataset.

In [19]:
data.dtypes

id                     int64
datetime              object
fare_amount          float64
pickup_datetime       object
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64
dtype: object

In [20]:
data.head(3)

,id,datetime,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1

In [21]:
# Create date column from pickup_datetime
data["date_time"] = pd.to_datetime(data["pickup_datetime"]).dt.date

In [22]:
data.head(3)

,id,datetime,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,date_time
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1,2015-05-07
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1,2009-07-17
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1,2009-08-24

In [24]:
data.dtypes

id                     int64
datetime              object
fare_amount          float64
pickup_datetime       object
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64
date_time             object
dtype: object