# **Data Preparation:**

In [1]:
import numpy as np
import pandas as pd 
import math 
import warnings

In [2]:
warnings.filterwarnings(action= "ignore")

In [13]:
data_train= pd.read_csv("train.csv", sep= ";")
data_train.shape

(45211, 17)

In [14]:
data_train.head(3)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no

In [15]:
data_test= pd.read_csv("test.csv", sep= ";")

In [23]:
data_test.head(3)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no

Now, we stack the two dataframes vertically:

In [19]:
# Stack both the dataframes vertically: 
data= pd.concat([data_train, data_test], axis= 0)
data.shape

(49732, 17)

In [20]:
data.head(3)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no

In [21]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [22]:
data.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

`Term deposits` are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Our money is invested for an agreed rate of interest over a fixed amount of time, or term. 

The bank has various outreach plans to sell term deposits to their customers such as `email marketing,` `advertisements`, `telephonic marketing`, and `digital marketing`.

Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call.

The data is related to `direct marketing campaigns (phone calls)` of a Portuguese banking institution. *`The classification goal is to predict if the client will subscribe to a term deposit (variable y).`*